spring:
  application:
    name: user_auth_service
  datasource:
    url: "jdbc:mysql://localhost:3306/car_marketplace_demo"
    username: "admin"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: userauth-service-listener
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
jwt:
  secret: ${JWT_SECRET}
  access-token:
    ttl-millis: 3600000
  refresh-token:
    ttl-millis: 86400000
server:
  port: 8080