services:
  mysql:
    image: mysql:latest
    container_name: car_marketplace_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: car_marketplace_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
volumes:
  mysql_data: