spring:
  application:
    name: post_listing_service
  datasource:
    url: "jdbc:mysql://localhost:3306/car_marketplace_demo"
    username: "admin"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: post-service-listener
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
server:
  port: 8082