spring:
  application:
    name: statistics_service
  datasource:
    url: "jdbc:mysql://localhost:3306/car_marketplace_demo"
    username: "admin"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      group-id: stats-service-listener
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
server:
  port: 8084